plugins {
    id "net.fabricmc.fabric-loom-remap"
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "DevLogin Maven"
                url = "https://maven.covers1624.net"
            }
        }
        filter {
            includeModule("net.covers1624", "DevLogin")
        }
    }
}

dependencies {
    minecraft libs.minecraft
    mappings(loom.layered {
        it.officialMojangMappings()
        it.parchment("org.parchmentmc.data:parchment-${libs.versions.parchment.minecraft.get()}:${libs.versions.parchment.mappings.get()}@zip")
    })
    localRuntime(libs.devlogin)

    modImplementation libs.fabric.loader
    modImplementation (libs.fabric.api) {
        exclude group: "net.fabricmc", module: "fabric-loader"
    }

    compileOnly project(":${rootProject.name}-Common")
    compileOnly libs.jetbrains.annotations

    compileOnly libs.autoservice.annotations
    annotationProcessor libs.autoservice

    modImplementation libs.sparkweave.fabric
    modImplementation (libs.resourcefulconfig.fabric) {
        exclude group: "net.fabricmc", module: "fabric-loader"
    }
    modImplementation libs.commonnetworking.fabric

    modImplementation libs.trinkets.fabric
    modImplementation libs.bundles.cca.fabric

    modCompileOnly libs.modmenu.fabric
    modLocalRuntime libs.modmenu.fabric

    modCompileOnly libs.figura.fabric
//    modLocalRuntime libs.figura.fabric
//    localRuntime libs.bundles.figura.runtime

    modCompileOnly variantOf(libs.emi.fabric) { classifier 'api' }
    modLocalRuntime libs.emi.fabric
}

loom {
    mods {
        "${mod_id}" {
            sourceSet("main")
        }
    }
    mixin {
        useLegacyMixinAp.set(false)
    }

    runs {
        configureEach {
            generateRunConfig = true
            systemProperties.put("mixin.debug", "true")
            systemProperties.put("sparkweave.debug", "true")
        }

        client {
            client()
            displayName = "Fabric Client"
            runDirectory = project.file("run")

            programArguments.addAll("--launch_target", "net.fabricmc.loader.impl.launch.knot.KnotClient")
            mainClass = "net.covers1624.devlogin.DevLogin"
        }

        server {
            server()
            displayName = "Fabric Server"
            runDirectory = project.file("run/server")
        }
    }
}

tasks.named("compileJava", JavaCompile) {
    source(project(":${rootProject.name}-Common").sourceSets.main.allJava)
}

tasks.named("javadoc", Javadoc) {
    source(project(":${rootProject.name}-Common").sourceSets.main.allJava)
}

tasks.named("sourcesJar", Jar) {
    from(project(":${rootProject.name}-Common").sourceSets.main.allSource)
}

processResources {
    from project(":${rootProject.name}-Common").sourceSets.main.resources
}
