plugins {
    alias libs.plugins.fabric.loom
}

dependencies {
    minecraft libs.minecraft
    mappings(loom.layered {
        it.officialMojangMappings()
        it.parchment("org.parchmentmc.data:parchment-${libs.versions.parchment.minecraft.get()}:${libs.versions.parchment.mappings.get()}@zip")
    })

    modImplementation libs.fabric.loader
    modImplementation (libs.fabric.api) {
        exclude group: "net.fabricmc", module: "fabric-loader"
    }

    compileOnly project(":Common")
    compileOnly libs.jetbrains.annotations

    compileOnly libs.autoservice.annotations
    annotationProcessor libs.autoservice

    modImplementation libs.sparkweave.fabric
    modImplementation (libs.resourcefulconfig.fabric) {
        exclude group: "net.fabricmc", module: "fabric-loader"
    }
    modImplementation libs.commonnetworking.fabric

    modImplementation libs.trinkets.fabric
    modImplementation libs.bundles.cca.fabric

    modCompileOnly libs.modmenu.fabric
    modLocalRuntime libs.modmenu.fabric

    modCompileOnly libs.figura.fabric
//    modLocalRuntime libs.figura.fabric
//    localRuntime libs.bundles.figura.runtime

    modCompileOnly variantOf(libs.emi.fabric) { classifier 'api' }
    modLocalRuntime libs.emi.fabric
}

loom {
    mods {
        "${mod_id}" {
            sourceSet("main")
        }
    }
    mixin {
        useLegacyMixinAp.set(false)
    }

    runs {
        configureEach {
            ideConfigGenerated(true)
            it.property('mixin.debug', 'true')
            it.property('sparkweave.debug', 'true')
        }

        client {
            client()
            setConfigName("Fabric Client")
            runDir("run")

            if (rootProject.hasProperty('mc_uuid')) {
                programArgs("--uuid", rootProject.mc_uuid)
            }

            if (rootProject.hasProperty('mc_username')) {
                programArgs("--username", rootProject.mc_username)
            }

            if (rootProject.hasProperty('mc_java_agent_path')) {
                vmArg("-javaagent:${rootProject.mc_java_agent_path}")
            }
        }

        server {
            server()
            setConfigName("Fabric Server")
            runDir("run/server")
        }
    }
}

tasks.named("compileJava", JavaCompile) {
    source(project(":Common").sourceSets.main.allJava)
}

tasks.named("javadoc", Javadoc) {
    source(project(":Common").sourceSets.main.allJava)
}

tasks.named("sourcesJar", Jar) {
    from(project(":Common").sourceSets.main.allSource)
}

processResources {
    from project(":Common").sourceSets.main.resources
}
