plugins {
    id "net.neoforged.moddev"
}

// need this before dependencies because it configures the plugin and creates additionalRuntimeClasspath configuration
neoForge.version = libs.versions.neoforge.get()

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    compileOnly project(":${rootProject.name}-Common")

    compileOnly libs.autoservice.annotations
    annotationProcessor libs.autoservice

    implementation libs.sparkweave.neoforge
    implementation libs.resourcefulconfig.neoforge
    implementation libs.commonnetworking.neoforge
    implementation libs.curios.neoforge
    implementation libs.caelus.neoforge

    compileOnly libs.figura.neoforge
//    localRuntime libs.figura.neoforge
//    localRuntime libs.bundles.figura.runtime

    compileOnly variantOf(libs.emi.neoforge) { classifier("api") }

    testImplementation libs.neoforge.testframework
}

test {
    useJUnitPlatform()
}

neoForge {
    parchment {
        minecraftVersion = libs.versions.parchment.minecraft.get()
        mappingsVersion = libs.versions.parchment.mappings.get()
    }

    mods {
        "${mod_id}" {
            sourceSet(project(":${rootProject.name}-Common").sourceSets.main)
            sourceSet(sourceSets.main)
        }
    }

    runs {
        configureEach {
            logLevel = org.slf4j.event.Level.DEBUG
            // The markers can be added/remove as needed separated by commas.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            systemProperty("forge.logging.markers", "REGISTRIES")
            systemProperty("mixin.debug", "true")
            systemProperty("sparkweave.debug", "true")

            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
            gameDirectory = project.file("run")
        }

        client {
            client()
            systemProperty("neoforge.enabledGameTestNamespaces", project.mod_id)

            devLogin = true
        }

        server {
            server()
            systemProperty("neoforge.enabledGameTestNamespaces", project.mod_id)

            programArgument("--nogui")
        }
    }

    unitTest {
        enable()

        testedMod = mods."${mod_id}"
    }
}

tasks.named("compileJava", JavaCompile) {
    source(project(":${rootProject.name}-Common").sourceSets.main.allJava)
}

tasks.named("javadoc", Javadoc) {
    source(project(":${rootProject.name}-Common").sourceSets.main.allJava)
}

tasks.named("sourcesJar", Jar) {
    from(project(":${rootProject.name}-Common").sourceSets.main.allSource)
}

processResources {
    from project(":${rootProject.name}-Common").sourceSets.main.resources
}
